name: Daily Carbox Inventory

on:
  schedule:
    # 11:30 UTC = 7:30 AM America/New_York (ET)
    - cron: "30 11 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python -m playwright install --with-deps chromium
      - run: python scrape_carbox.py
      - name: Commit reports
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add reports/*.csv || true
          git commit -m "Daily Carbox inventory $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push
